version: "3.4"

services:

  backend:
    build:
      context: ./back/
    ports:
      - "5000:5000"
    volumes:
      - "./back:/code"

  frontend:
    build:
      context: ./front/
    ports:
      - "8080:8080"
    volumes:
      - "./front:/code"
